### ISSUE TITLE
doesnt' refresh automatically

### ISSUE THREAD

**Issue by GoogleCodeExporter** [miscalencu/Google-Chrome-Simple-Weather#11]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?
should refresh in the background  

What version of the product are you using? On what operating system?

chrome 10.0.648.204,windows 7 ultimae service pack 1
Please provide any additional information below.


```

Original issue reported on code.google.com by `cw138...@gmail.com` on 13 Apr 2011 at 4:37

**Comment by miscalencu** [comment]
I suggest you check the new Simple Weather extension at https://chrome.google.com/webstore/detail/simple-weather/dkgcomhcmhlbdokplmbpkejkojkmjglg/support. It is based on the ond one but totally different in the same time. :) Enjoy!
