### ISSUE TITLE
does not update

### ISSUE THREAD

**Issue by GoogleCodeExporter** [miscalencu/Google-Chrome-Simple-Weather#12]
```
What version of the product are you using? On what operating system?

latest/ mac.

doesn't update. i've tried setting various refresh options. when i click the 
extension it then updates.
```

Original issue reported on code.google.com by `jeffrey.blattman@gmail.com` on 13 Sep 2011 at 11:14

**Comment by miscalencu** [comment]
I suggest you check the new Simple Weather extension at https://chrome.google.com/webstore/detail/simple-weather/dkgcomhcmhlbdokplmbpkejkojkmjglg/support. It is based on the ond one but totally different in the same time. :) Enjoy!
