### ISSUE TITLE
Malicious website access

### ISSUE THREAD

**Issue by greatvc** [miscalencu/Google-Chrome-Simple-Weather#15]
Hi, today i open chrome and malware bytes anti-malware software went crazy with access to suspicious sites like brainlog.top, clearbrain.top and so on.
I disabled one by one my extensions and the Simple weather extension was the problem. Once i disabled it  the alerts went away, the moment i enable it again and the extension try to connect to sites the alerts begun. Something is wrong with the links or i don't know.

Thought you should known.

**Comment by miscalencu** [comment]
Sorry, I no longer own that extension. You can find the original one (last version that I maintained) in the Simple Weather branch of this repository (https://github.com/miscalencu/Google-Chrome-Simple-Weather/tree/SimpleWeather). You can download it and install it from here at anytime (http://superuser.com/questions/247651/how-does-one-install-an-extension-for-chrome-browser-from-the-local-file-system).
