### ISSUE TITLE
Chrome extension doesn't load

### ISSUE THREAD

**Issue by hollywood2311** [miscalencu/Google-Chrome-Simple-Weather#16]
When I use the Chrome extension button in the upper right corner, this is what I see:

![chromeextension](https://cloud.githubusercontent.com/assets/25941335/23191138/00c31798-f86a-11e6-81ce-bbd822e828ca.jpg)

I enabled Flash, but still get the same blank blue box. Using Chrome version 56.0.2924.87 on Windows 10 Home. If I hover the cursor over the button, it does show current weather conditions. Thanks.

**Comment by miscalencu** [comment]
Hi,

I no longer own the online extension. If you still want to use it, please get the files at https://github.com/miscalencu/Google-Chrome-Simple-Weather/tree/SimpleWeather, install the extension from the local machine and let me know if you still have the same issues.

Regards,
George
