### ISSUE TITLE
characters not displaying correctly on Linux systems

### ISSUE THREAD

**Issue by GoogleCodeExporter** [miscalencu/Google-Chrome-Simple-Weather#2]
```
On some systems like Linux, native alphabet is just not shown when the 
specified font cannot handle native alphabet.

TO DO:
1. Add options for different fonts.


```

Original issue reported on code.google.com by `george.m...@gmail.com` on 29 Jan 2010 at 2:12

**Comment by miscalencu** [comment]
I suggest you check the new Simple Weather extension at https://chrome.google.com/webstore/detail/simple-weather/dkgcomhcmhlbdokplmbpkejkojkmjglg/support. It is based on the old one but totally different in the same time. :) Enjoy!
