### ISSUE TITLE
Add disabled states to location change buttons

### ISSUE THREAD

**Issue by GoogleCodeExporter** [miscalencu/Google-Chrome-Simple-Weather#5]
```
The title says it all, it would be nice and informative.
```

Original issue reported on code.google.com by `go.x...@gmail.com` on 9 Jun 2010 at 7:15

**Comment by miscalencu** [comment]
I suggest you check the new Simple Weather extension at https://chrome.google.com/webstore/detail/simple-weather/dkgcomhcmhlbdokplmbpkejkojkmjglg/support. It is based on the old one but totally different in the same time. :) Enjoy!
