### ISSUE TITLE
Weather.com link button doesn't work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [miscalencu/Google-Chrome-Simple-Weather#6]
```
Since Weather.com has updated their website, the link to get more details at 
weather.com no longer works.

Clicking the button takes me here: http://www.weather.com/weather/today/chicago

This is the actual link that works if you search on weather.com:
http://www.weather.com/weather/today/USIL0225:1:US
```

Original issue reported on code.google.com by `czec...@gmail.com` on 19 Jul 2010 at 1:22

**Comment by miscalencu** [comment]
I suggest you check the new Simple Weather extension at https://chrome.google.com/webstore/detail/simple-weather/dkgcomhcmhlbdokplmbpkejkojkmjglg/support. It is based on the old one but totally different in the same time. :) Enjoy!

Also, Weather.com link is more accurate now!
